# Generated by Django 4.2.23 on 2025-08-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regiones',
            new_name='Region',
        ),
    ]
