# Generated by Django 4.2.23 on 2025-08-30 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_regiones_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudarriendo',
            name='arrendatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
