# Generated by Django 4.2.23 on 2025-08-28 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_solicitudarriendo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='Regiones',
        ),
        migrations.CreateModel(
            name='PerfilUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('ARRENDATARIO', 'Arrendatario'), ('ARRENDADOR', 'Arrendador')], default='ARRENDATARIO', max_length=20)),
                ('rut', models.CharField(max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
